name: i_love_iruka
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.4+8

environment:
  sdk: ">=2.1.0 <3.0.0" 

dependencies:
  flutter:
    sdk: flutter
  polygon_clipper: ^1.0.2
  percent_indicator: ^2.1.1+1
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  qr_flutter: ^3.0.1
  font_awesome_flutter: ^8.5.0
  carousel_pro: ^1.0.0
  url_launcher: ^5.2.5
  grouped_listview: ^0.0.2
  dio: ^3.0.4
  bloc: ^2.0.0
  http: ^0.12.0+2
  flutter_bloc: ^2.0.0
  fluttertoast: ^3.1.3
  image_picker: ^0.6.1+10
  path_provider: ^1.4.0
  path: ^1.6.4
  provider: ^3.1.0+1
  keyboard_avoider: ^0.1.2
  shared_preferences: ^0.5.4+3
  carousel_slider: ^1.3.1
  # cached_network_image: ^1.1.3
  intl: ^0.16.0
  division: ^0.8.7+2
  flutter_datetime_picker: ^1.3.1
  flutter_launcher_icons: ^0.7.4
  auto_route: ^0.2.2
  states_rebuilder: ^1.11.2
  share: ^0.6.3+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  auto_route_generator: ^0.2.2
  build_runner: ^1.7.3

flutter_icons:
  android: true
  ios: true
  image_path: "images/assets/mobile_app_logo_2.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
   - images/assets/pet_grooming.png
   - images/assets/pet_hotel.png
   - images/assets/pet_school.png
   - images/assets/pet_shop.png
   - images/assets/pet_taxi.png
   - images/assets/point_food.png
   - images/assets/point_services.png
   - images/assets/profile_placeholder.png
   - images/assets/iruka_logo.png
   - images/assets/iruka_petcare_white.png
   - images/assets/medal.png
   - images/assets/ratio11.png
   - images/assets/iruka_cloud.png
   - images/assets/pet-spa.png
   - images/assets/youtube.png
   - images/assets/whatsapp.png
   - images/assets/instagram.png
   - images/assets/global.png
   - images/assets/telephone.png
   - images/assets/iruka_logo2.jpg
   - images/assets/iruka_launcher_2.jpg
   - images/assets/mobile_app_logo_2.jpg
   
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
