name: i_love_iruka
description: A new Flutter project.
version: 1.2.2+13

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^6.1.1
  cached_network_image: ^2.2.0+1
  carousel_slider: ^2.0.0
  cupertino_icons: ^0.1.2
  dartz: ^0.9.1
  date_time_picker: ^1.1.1
  dio: ^3.0.9
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.4+3
  firebase_messaging: ^6.0.9
  flushbar: ^1.10.4
  flutter_bloc: ^6.1.1
  flutter_datetime_picker: ^1.3.8
  flutter_launcher_icons: ^0.7.4
  fluttertoast: ^3.1.3
  font_awesome_flutter: ^8.5.0
  freezed_annotation: ^0.12.0
  geolocator: ^5.2.1
  get: ^3.24.0
  get_it: ^4.0.2
  get_storage: ^1.4.0
  google_fonts: ^1.0.0
  image_downloader: ^0.19.1
  image_picker: ^0.6.1+10
  injectable: ^1.0.7
  intl: ^0.16.1
  json_serializable: ^3.3.0
  material_design_icons_flutter: ^4.0.5145
  path: ^1.6.4
  path_provider: ^1.4.0
  qr_flutter: ^3.0.1
  rflutter_alert: ^1.0.3
  share: ^0.6.3+5
  url_launcher: ^5.2.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.13
  freezed: ^0.12.7
  injectable_generator: ^1.0.7

flutter_icons:
  android: true
  ios: true
  image_path: "images/assets/mobile_app_logo_2.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
dependency_overrides: null
# analyzer: '0.39.17'
# build_resolvers: '1.3.10'
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/assets/pet_grooming.png
    - images/assets/pet_hotel.png
    - images/assets/pet_school.png
    - images/assets/pet_shop.png
    - images/assets/pet_taxi.png
    - images/assets/point_food.png
    - images/assets/point_services.png
    - images/assets/profile_placeholder.png
    - images/assets/iruka_logo.png
    - images/assets/iruka_petcare_white.png
    - images/assets/medal.png
    - images/assets/ratio11.png
    - images/assets/iruka_cloud.png
    - images/assets/pet-spa.png
    - images/assets/youtube.png
    - images/assets/whatsapp.png
    - images/assets/instagram.png
    - images/assets/global.png
    - images/assets/telephone.png
    - images/assets/iruka_logo2.jpg
    - images/assets/iruka_launcher_2.jpg
    - images/assets/mobile_app_logo_2.jpg
    - images/assets/no_image.jpg
    - images/assets/refresh.png
    - images/assets/image_placeholder.png

    - images/dev_images/petting.png
    - images/dev_images/background_petting.png
    - images/dev_images/signin_decoration.png
    - images/dev_images/forgot_password_decoration.png
    - images/dev_images/forgot_password_bg_show.png
    - images/dev_images/forgot_password_image.png

    - images/dev_images/yellow_clippath1.png
    - images/dev_images/yellow_clippath2.png
    - images/dev_images/yellow_clippath3.png

    - images/dev_images/blue_clippath1.png
    - images/dev_images/blue_clippath2.png
    - images/dev_images/blue_clippath3.png

    - images/dev_images/bronze_clippath1.png
    - images/dev_images/bronze_clippath2.png
    - images/dev_images/bronze_clippath3.png
    - images/assets/iruka_petcare_color.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
